import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Shared navbar */}
        <header className="flex gap-8 bg-gray-300 p-6 justify-around">
          <Link href={"/Home"}>Home</Link>
          <Link href={"/AboutUs"}>About Us</Link>
          <Link href={"/ContactUs"}>Contact Us</Link>
          <Link href={"/Form"}>Form</Link>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
